export const recommendedLibraries = {
    ecommerce: [
        "React",
        "Redux",
        "Material-UI",
        "Axios",
        "React Hook Form",
        "Formik",
        "React Query",
        "Stripe",
        "react-icons",
        "react-toastify",
        "classnames"
    ],
    blogs: [
        "Express.js",
        "Mongoose",
        "Passport.js",
        "React",
        "Markdown-it",
        "Next.js",
        "React Markdown",
        "moment",
        "react-syntax-highlighter",
        "Sass"
    ],
    contentManagement: [
        "React",
        "Strapi",
        "Gatsby",
        "GraphQL",
        "Tailwind CSS",
        "Apollo Client",
        "Formik",
        "Yup",
        "react-router-dom",
        "react-query"
    ],
    portfolio: [
        "React",
        "Styled Components",
        "Framer Motion",
        "React Router",
        "Gatsby",
        "Formik",
        "Yup",
        "Sass",
        "react-intersection-observer",
        "react-scroll"
    ],
    socialMedia: [
        "React",
        "Firebase",
        "Redux",
        "Socket.io",
        "Ant Design",
        "React Router",
        "axios",
        "moment",
        "react-query",
        "react-redux-firebase"
    ],
    elearning: [
        "Node.js",
        "MongoDB",
        "React",
        "Chart.js",
        "Next.js",
        "Styled Components",
        "React Query",
        "React Hook Form",
        "Formik",
        "Yup"
    ],
    mobileApp: [
        "React Native",
        "Expo",
        "Redux",
        "React Navigation",
        "React Native Paper",
        "Axios",
        "Formik",
        "Yup",
        "Reanimated",
        "React Native Gesture Handler"
    ],
    staticSite: [
        "HTML5",
        "CSS3",
        "JavaScript",
        "Bootstrap",
        "Gatsby",
        "Tailwind CSS",
        "jQuery",
        "Sass",
        "FontAwesome",
        "Parcel"
    ],
    fullStackApp: [
        "React",
        "Node.js",
        "Express.js",
        "MongoDB",
        "JWT",
        "Redux",
        "Mongoose",
        "Material-UI",
        "Axios",
        "React Router"
    ],
    dataScienceApp: [
        "React",
        "D3.js",
        "Plotly.js",
        "NumPy",
        "Pandas",
        "Scikit-learn",
        "TensorFlow",
        "Flask",
        "Dash",
        "Jupyter"
    ],
    realTimeChat: [
        "React",
        "Socket.io",
        "Node.js",
        "Express.js",
        "Redis",
        "Firebase",
        "React Router",
        "Tailwind CSS",
        "Formik",
        "Yup"
    ],
    travelBooking: [
        "React",
        "Next.js",
        "GraphQL",
        "Apollo Client",
        "Leaflet",
        "Stripe",
        "axios",
        "React Router",
        "Material-UI",
        "React Query"
    ],
    healthCareApp: [
        "React",
        "Redux",
        "Material-UI",
        "D3.js",
        "Axios",
        "Formik",
        "Yup",
        "react-hook-form",
        "styled-components",
        "react-toastify"
    ],
    cryptoWallet: [
        "React",
        "Redux",
        "Material-UI",
        "Axios",
        "Formik",
        "Yup",
        "react-icons",
        "react-toastify",
        "classnames"
    ],
    fitnessApp: [
        "React",
        "Redux",
        "Material-UI",
        "Chart.js",
        "Axios",
        "Formik",
        "Yup",
        "react-hook-form",
        "styled-components",
        "react-toastify"
    ],
    realEstate: [
        "React",
        "Redux",
        "Material-UI",
        "Axios",
        "Formik",
        "Yup",
        "react-icons",
        "react-toastify",
        "classnames"
    ],
    iotManagement: [
        "React",
        "Redux",
        "Material-UI",
        "Axios",
        "Formik",
        "Yup",
        "react-icons",
        "react-toastify",
        "classnames"
    ],
    newsAggregator: [
        "React",
        "Redux",
        "Material-UI",
        "Axios",
        "Formik",
        "Yup",
        "react-icons",
        "react-toastify",
        "classnames"
    ],
    musicStreaming: [
        "React",
        "Redux",
        "Material-UI",
        "Axios",
        "Formik",
        "Yup",
        "react-icons",
        "react-toastify",
        "classnames"
    ]
};
